version: "3"
services:
  client:
    image: "542236349330.dkr.ecr.eu-south-1.amazonaws.com/multi-client:latest"
    mem_limit: 128m
    hostname: client
  server:
    image: "542236349330.dkr.ecr.eu-south-1.amazonaws.com/multi-server:latest"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "542236349330.dkr.ecr.eu-south-1.amazonaws.com/multi-worker:latest"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "542236349330.dkr.ecr.eu-south-1.amazonaws.com/multi-nginx:latest"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"